### PR TITLE
Closes #68 Add cart related models to the SDK

### LINKED ISSUE #68: Add cart related models to the SDK
The goal is to have cart related models available in all endpoints `Cart` conforms to.

It'd also be useful to keep the ability to access json dictionary response. Both json dictionary, and model should be accessible from the `result` closure.

These changes should be made in a way to still support quick and easy creation of a new class / struct for any endpoint conforming to specific endpoint actions.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
_Note:_ Tests are still being added for this feature.

Besides introducing a lot of models related to cart endpoint, this PR introduces support for models across endpoints, specifically for: `QueryEndpoint, ByIdEndpoint, CreateEndpoint, UpdateEndpoint, DeleteEndpoint`.

We'll also be leaving an option for each endpoint for the SDK users to consume raw dictionary, in case of an API change, etc. In general, for each endpoint / action, we have 2 possible `result` handlers, one containing model and the other one dictionary response.
Just to quickly illustrate that with active cart:

Dictionary:
```swift
Cart.active(dictionaryResult: { result in
    if let response = result.response, let activeCartId = response["id"] {
        // The response is an instance of Dictionary type
    }
})
```
Model:
```swift
Cart.active(result: { result in
    if let cart = result.response, result.isSuccess {
        // cart.cartState == .active would of course return true
    }
})
```

Another important thing to note here is that `Draft` models aren't included. I thought this PR got too many changes, so for the sake of reviewing (and implementation), I was thinking to add `Draft` models after this one gets merged.
@cneijenhuis WDYT?

### CODE REVIEW

**Comment by cneijenhuis** [comment]
Great we are making progress on this 👍 Some questions though 😢 

Correct me if I'm wrong, but I think we now lost the possibility to quickly create a class for an endpoint that just returns JSON, like
```swift
class Messages: QueryEndpoint {
  static let path = "messages"
}
```
?

Another thing I want to double-check with the other SDK devs is whether it is useful to be able to access the JSON response in addition to the model.

**Comment by nikola-mladenovic** [comment]
> Correct me if I'm wrong, but I think we now lost the possibility to quickly create a class for an endpoint that just returns JSON

Right now, if a user would need to quickly create a class for an endpoint that just returns JSON, it would be possible like this:
```swift
class Messages: QueryEndpoint, Mappable {
    
    typealias ResponseType = Messages
    static let path = "messages"
    
    required init?(map: Map) {}
    
    // MARK: - Mappable
    
    public func mapping(map: Map) {}
}
```

I do agree that it's rather important we keep the ability of quick endpoint class creations, so before we release the next SDK version, I wanned to introduce a type that will conform to `Mappable` but have no mapping, so our `Messages` class would look like:

```swift
class Messages: QueryEndpoint {
    
    typealias ResponseType = NoMapping
    static let path = "messages"
}
```

**Comment by nikola-mladenovic** [comment]
> Another thing I want to double-check with the other SDK devs is whether it is useful to be able to access the JSON response in addition to the model.

Yes, please do let me know. Perhaps I misunderstood, but I though we'd also want to keep that ability. If not, we can remove the support 👍 😊

**Comment by cneijenhuis** [comment]
What I meant was that both are accessible at the same time / with a single API request. So you'd have something like `response.model` and `response.json`.

I checked with Jens and it can be useful if e.g. the model is outdated, and you need to access a new/extra field. You still want to work with the model in most of the cases, but for this single field you'd fall back to the JSON.

With that, we could go back to a single function - WDYT?

I like the idea of `NoMapping` 👍

**Comment by nikola-mladenovic** [comment]
> What I meant was that both are accessible at the same time / with a single API request. So you'd have something like response.model and response.json.

Let's do that 👍

**Comment by nikola-mladenovic** [comment]
I've updated the endpoints logic, so how we have:

Dictionary:
```swift
Cart.active(result: { result in
    if let response = result.json, let activeCartId = response["id"] {
        // The response is an instance of Dictionary type
    }
})
```
Model:
```swift
Cart.active(result: { result in
    if let cart = result.model, result.isSuccess {
        // cart.cartState == .active would of course return true
    }
})
```

**Comment by cneijenhuis** [comment]
Looks great! 🏆 

`NoMapping` is coming next, I guess?

**Comment by nikola-mladenovic** [comment]
Added `NoMapping` type for easy endpoint creation where no domain model exists. I've also updated our tests to use this type any private endpoint they declare for local testing scope, e.g:
```swift
private class TestProductProjections: ByIdEndpoint, QueryEndpoint {
    public typealias ResponseType = NoMapping
    static let path = "product-projections"
}
```

After all the checks complete, I'll proceed with merge, and we'll tackle `Draft` models in another PR.

**Pull request merged**
