### PR TITLE
Closes #67 , closes #66 Add product related models, add product type and categories related models

### LINKED ISSUE #66: Add product related models and drafts to the SDK

### LINKED ISSUE #67: Add product type, categories, customer and order related models and drafts to the SDK

### PR DESCRIPTION
**Pull request by nikola-mladenovic**

### CODE REVIEW

**Comment by nikola-mladenovic** [comment]
I've updated PR with `Customer` model. I'm also going to add `Order` related models, as a part of this PR. That practically means, we'll have models for all endpoints we support currently in the SDK.

@cneijenhuis - do you want me to create issues for customer and order related models for our reference?

**Comment by cneijenhuis** [comment]
You could also change the existing ticket to include the other models, if you want to.

Please ping me when I should do a final review 😉

**Comment by nikola-mladenovic** [comment]
Added customer and order related models and order draft. I've also updated title for issue #67 to match what we've done here.

**Comment by cneijenhuis** [comment]
Great 👍

**Pull request merged**
