### PR TITLE
Remove ObjectMapper

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
We finally don't have any dependencies 🎉 

Removing ObjectMapper was a bit tedious, most parts were straightforward, but the tricky part was related to the occurrences of `[String: Any]` in our codebase (e.g custom objects, `Attribute`'s `value` field, etc).
`Codable` protocol, along with `Decoder` and `Encoder` don't allow us to leave them as they were before. In the upcoming days I'm going to see what would be the best way to model our custom objects, as well as some fields like `Attribute`'s `value` field that can have different structures in different responses. I'll try to generalize something we [have](https://github.com/commercetools/commercetools-sunrise-ios/blob/30e99c5049784a4b820f8beb6f9b05d26e31102d/Sunrise/Models/Attribute.swift) here in the Sunrise app.

I also added an `enum` that would be used for representing any values we don't have completely modeled:
```swift
public enum JsonValue: Codable {
    case bool(value: Bool)
    case int(value: Int)
    case double(value: Double)
    case string(value: String)
    case dictionary(value: [String: JsonValue])
    case array(value: [JsonValue])
    case unknown
}
```

### CODE REVIEW

**Comment by nikola-mladenovic** [comment]
I'm also going to update the `README.md` with the required Xcode version, Swift version, and add the badge for Linux support ☺️

**Comment by nikola-mladenovic** [comment]
Here's the reasoning behind it:
- Trying to `struct`s over `class`es, as it's generally safer and better to deal with value types in Swift;
- There're some cases where we have to use `class`es (e.g `Category`, because it references other `Category` types: `parent`, `ancestors`, and the `struct` wouldn't do the job here).
- Swift has automatic init generation for all of your properties for `struct`s, and not for classes. That is the reason why we have `init`s for them.
- We also put `init`s for `Draft` methods even though they're `struct` mostly for convenience: the generated `init` we get doesn't have default values for optional parameters, which practically means if you want to init a `CartDraft` only with `currency` set, if it wasn't for the initializer I wrote with default `nil` values, you'd have to specify each and every argument and set it value to `nil`.

WDYT about this? I'm open to any suggestions / changes?

**Comment by nikola-mladenovic** [comment]
@cneijenhuis I've added `key` property to `Customer` and `TaxCategory` in this PR so I don't bother you with the new one because of this trivial commit.

**Comment by cneijenhuis** [comment]
ok 👍

**Pull request merged**
