### PR TITLE
Closes #174 Support for external user ID

### LINKED ISSUE #174: Support X-External-User-ID header
Since client applications can now use a new HTTP header, X-External-User-ID, when making API calls to track changes initiated by a specific user’s actions, we should add support for thta in the SDK.

@cneijenhuis should we include any limitations on this, or simply let the app set this header value at any point in time, and use it for all subsequent requests, until it's unset?

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
- [x] Exposed `Commercetools.externalUserId` property to SDK clients;
- [x] Tested `createdBy.externalUserId` & `lastModifiedBy!.externalUserId` when using `X-External-User-ID`;
- [x] Updated readme.

@cneijenhuis if you get a chance, feel free to have a glance.

### CODE REVIEW

**Comment by cneijenhuis** [comment]
Sorry, I'm not the right person to review this :(

Reading the Readme, I don't understand why we switch between `user` and `customer` in our wording here. If the feature is meant to be used with `customer` accounts, we should name the header accordingly... but I'm not sure whether that was the intention in the first place.

**Comment by nikola-mladenovic** [comment]
Good catch, that was my mistake - IMO we should always use ‘user’ - will update the readme.

Thanks for having a look & for the feedback 👍

**Comment by cneijenhuis** [comment]
No, the iOS SDK should always use `customer` - `customer` is used for a person who uses the shop frontend. `user` is used for a person who uses e.g. the Merchant Center.

**Comment by nikola-mladenovic** [comment]
To make our nomenclature consistent across Swift SDK, I’ll update the properly to be _externalCustomerId_ along with related text from readme, and codebase comments / documentation.

**Comment by cneijenhuis** [comment]
Sorry for the forth-and-back on this one - again, I'm not the right person, please double-check with your PO and the PO who was responsible for the header.

I'm not sure whether iOS SDK should use this at all. https://docs.commercetools.com/http-api-types#client-logging makes a distinction between `customer` and `anonymousId` (which is already implicitly supported by the iOS SDK) and the `externalUserId`. The latter is targeted towards the Merchant Users, as far as I can tell.

Due to the used tokens, the iOS SDK will always set either `customer` or `anonymousId`. Please double-check what the point is of setting another `externalUserId`, because I don't see it (but again, this isn't my feature, so I may simply not know).

**Comment by nikola-mladenovic** [comment]
After talking with @FreddieK the main use case for `X-External-User-ID` is for tracking changes triggered from external systems, programmatic updates to our entities though using API clients, etc.

Therefore, setting the value for this header wouldn't be useful for regular mobile client use-cases. It would make sense for some use-cases where we use the Swift SDK for lambda functions handling notifications and other isolated tasks, but IMO we should only have mobile client features on our master branch. Therefore, it makes sense not to merge this.

**Pull request closed without merging**
